nom : CI/CD Pipeline 
on :
   push :
     branches : [ main ] 

jobs :
   intégration continue :
     run-on : ubuntu-latest 
    étapes :
       # Étape 1 
      - utilise : actions/checkout@v2 
      # Étape 2 
      - nom : Configurer JDK 11 
        utilisations : actions/setup-java@v2 
        avec :
           java-version : ' 11 '
           distribution : 'adopt ' 
      # Étape 3 
      - nom : Build Application and Run unit Test 
        run : mvn -B test --file student-service/pom.xml Continuous 
        
  -deployment :
     runs-on : ubuntu-latest 
    need : [continuous-integration] 
    if : github.ref == 'refs/heads/main' 
    étapes :
      # Étape 1 
      - nom : Configurer les informations d'identification AWS 
        utilise : aws-actions/configure-aws-credentials@v1 
        avec :
           aws-access-key-id :${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region : ${{ secrets.AWS_REGION }} 
     # Étape 2 
      - nom : Create CodeDeploy Deployment 
        id : deploy 
        run : | 
          aws deploy create-deployment \ 
            --application-name Git_Application \ 
            --deployment-group-name development_gropup \ 
            --deployment-config-name CodeDeployDefault.OneAtATime \ 
            --github-location repository=${{ github.repository }},commitId =${{ github.sha }}
